# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dimroc/ubuntu14.04"

  config.vm.provision "docker", version: "1.1", images: ["ubuntu:14.04"]
  config.vm.provision "shell", inline: 'sudo apt-get update'
  config.vm.provision "shell", path: 'install_cli_helpers.sh'
  config.vm.provision "shell", path: 'install_ruby.sh'

  config.vm.define "base"
end
