# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :virtualbox do |vbox, override|
    override.vm.box = "dimroc/ubuntu14.04"
  end

  config.vm.provider :aws do |aws, override|
    override.vm.box = "dimroc/awsdummy"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/elasticdocker.pem"

    aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
    aws.secret_access_key = ENV["AWS_SECRET_ACCESS_KEY"]
    aws.keypair_name = 'elasticdocker'

    aws.ami = "ami-1d8c9574"
    aws.instance_type = "t2.micro"

    # Manually created VPC and subnet prior to running vagrant up.
    # Make sure security group associated with subnet allows SSH.
    aws.subnet_id = "subnet-beeb15c9" 
    aws.elastic_ip = true
    aws.associate_public_ip = true
    aws.tags = { "Name" => "vagrantaws-base" }
  end

  config.vm.provision "docker", version: "1.1", images: ["ubuntu:14.04"]
  config.vm.provision "shell", inline: 'sudo apt-get update'
  config.vm.provision "shell", path: 'install_cli_helpers.sh'
  config.vm.provision "shell", path: 'install_ruby.sh'

  config.vm.define "base"
end
