# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :virtualbox do |vbox, override|
    override.vm.box = "dimroc/elasticdocker-base"
  end

  config.vm.define "server", primary: true do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "172.20.20.10"
    server.vm.provision "shell", path: 'server.sh'

    server.vm.provider :aws do |aws, override|
      override.vm.box = "dummy"

      aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
      aws.secret_access_key = ENV["AWS_SECRET_ACCESS_KEY"]
      aws.keypair_name = 'dimitrib'

      aws.ami = "ami-1d8c9574"
      aws.instance_type = "t2.micro"

      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "~/.ssh/dimitrib.qa.pem"
    end
  end

  config.vm.define "agent" do |agent|
    agent.vm.hostname = "agent"
    agent.vm.network "private_network", ip: "172.20.20.11"
    agent.vm.provision "shell", path: 'agent.sh'

    agent.vm.provider :aws do |aws, override|
      override.vm.box = "dummy"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "~/.ssh/dimitrib.qa.pem"

      aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
      aws.secret_access_key = ENV["AWS_SECRET_ACCESS_KEY"]
      aws.keypair_name = 'dimitrib'

      aws.ami = "ami-1d8c9574"
      aws.instance_type = "c3.large"
    end
  end
end
